Speech Emotion Identification

Done by:

S. Divya

19251A05B5

GNITS

**Import required libraries**

In [ ]:
import librosa
import soundfile
import pandas as pd
import os, glob, pickle
import numpy as np
from tqdm import tqdm
from scipy.io import wavfile
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

**Mount the dataset file for importing the dataset**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


**Loading the Dataset (Ravdess)**

In [ ]:
os.listdir(path='drive/MyDrive/dataset')
def getListOfFiles(dirName):
    listOfFile=os.listdir(dirName)
    allFiles=list()
    for entry in listOfFile:
        fullPath=os.path.join(dirName, entry)
        if os.path.isdir(fullPath):
            allFiles=allFiles + getListOfFiles(fullPath)
        else:
            allFiles.append(fullPath)
    return allFiles

dirName = 'drive/MyDrive/dataset'
listOfFiles = getListOfFiles(dirName)
len(listOfFiles)

1569

**Cleaning the dataset**

DOWN SAMPLING OF AUDIO FILES IS DONE AND PUT MASK OVER IT AND DIRECT INTO CLEAN FOLDER
MASK IS TO REMOVE UNNECESSARY EMPTY VOIDES AROUND THE MAIN AUDIO VOICE

In [ ]:
def envelope(y , rate, threshold):
    mask=[]
    y=pd.Series(y).apply(np.abs)
    y_mean = y.rolling(window=int(rate/10) ,  min_periods=1 , center = True).mean()
    for mean in y_mean:
        if mean>threshold:
            mask.append(True)
        else:
            mask.append(False)
    return mask

**Extract features (mfcc, chroma, mel) from a sound file**

In [ ]:
def extract_feature(file_name, mfcc, chroma, mel):
    with soundfile.SoundFile(file_name) as sound_file:
        X = sound_file.read(dtype="float32")
        sample_rate=sound_file.samplerate
        if chroma:
            stft=np.abs(librosa.stft(X))
        result=np.array([])
        if mfcc:
            mfccs=np.mean(librosa.feature.mfcc(y=X, sr=sample_rate, n_mfcc=40).T, axis=0)
        result=np.hstack((result, mfccs))
        if chroma:
            chroma=np.mean(librosa.feature.chroma_stft(S=stft, sr=sample_rate).T,axis=0)
        result=np.hstack((result, chroma))
        if mel:
            mel=np.mean(librosa.feature.melspectrogram(X, sr=sample_rate).T,axis=0)
        result=np.hstack((result, mel))
    return result

Emotions in the dataset

In [ ]:
emotions={
  '01':'neutral',
  '02':'calm',
  '03':'happy',
  '04':'sad',
  '05':'angry',
  '06':'fearful',
  '07':'disgust',
  '08':'surprised'
}
#These are the emotions User wants to observe more :
observed_emotions=['calm', 'happy', 'angry', 'disgust']

 **Loading the clean data and extracting the data from it**

In [ ]:
from glob import glob
import os
import glob
def load_data(test_size=0.33):
    x,y=[],[]
    answer = 0
    for file in glob.glob('drive/MyDrive/dataset//Actor_*//*.wav'):
        file_name=os.path.basename(file)
        emotion=emotions[file_name.split("-")[2]]
        if emotion not in observed_emotions:
            answer += 1
            continue
        feature=extract_feature(file, mfcc=True, chroma=True, mel=True)
        x.append(feature)
        y.append([emotion,file_name])
    return train_test_split(np.array(x), y, test_size=test_size, random_state=0)

**Splitting the dataset into test and trial data**

In [ ]:
x_train,x_test,y_train,y_test=load_data(test_size=0.25)
print(np.shape(x_train),np.shape(x_test), np.shape(y_train),np.shape(y_test))
y_test_map = np.array(y_test).T
y_test = y_test_map[0]
test_filename = y_test_map[1]
y_train_map = np.array(y_train).T
y_train = y_train_map[0]
train_filename = y_train_map[1]
print(np.shape(y_train),np.shape(y_test))
print(*test_filename,sep="\n")

(576, 180) (192, 180) (576, 2) (192, 2)
(576,) (192,)
03-01-03-01-01-01-01.wav
03-01-07-01-02-01-22.wav
03-01-02-01-02-02-22.wav
03-01-05-01-02-02-19.wav
03-01-07-01-02-01-05.wav
03-01-05-01-02-02-22.wav
03-01-03-01-02-01-14.wav
03-01-07-02-02-02-06.wav
03-01-03-02-01-01-11.wav
03-01-07-01-02-01-21.wav
03-01-07-02-01-02-19.wav
03-01-03-01-01-01-12.wav
03-01-07-01-01-01-23.wav
03-01-05-01-01-02-06.wav
03-01-02-02-01-02-03.wav
03-01-07-02-01-02-21.wav
03-01-03-02-01-02-17.wav
03-01-05-02-02-01-18.wav
03-01-05-01-01-02-07.wav
03-01-07-01-01-02-13.wav
03-01-02-02-01-02-08.wav
03-01-02-01-02-01-06.wav
03-01-02-02-01-02-17.wav
03-01-07-02-02-01-13.wav
03-01-07-01-02-01-19.wav
03-01-02-02-02-02-06.wav
03-01-02-02-01-01-15.wav
03-01-02-01-02-02-03.wav
03-01-02-01-02-02-24.wav
03-01-03-01-01-02-10.wav
03-01-07-02-02-01-23.wav
03-01-02-02-02-01-08.wav
03-01-05-01-02-02-01.wav
03-01-07-02-01-01-13.wav
03-01-05-01-01-01-11.wav
03-01-02-01-02-02-11.wav
03-01-02-01-01-01-01.wav
03-01-07-01-02-02-10.

**Initialize the Multi Layer Perceptron Classifier**

In [ ]:
model=MLPClassifier(alpha=0.01, batch_size=256, epsilon=1e-08, hidden_layer_sizes=(300,), learning_rate='adaptive', max_iter=500)

**Train the model**

In [ ]:
model.fit(x_train,y_train)

MLPClassifier(alpha=0.01, batch_size=256, hidden_layer_sizes=(300,),
              learning_rate='adaptive', max_iter=500)

**Predicting the y_test values using the loaded Model**

In [ ]:
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_true=y_test, y_pred=y_pred)
print("Accuracy of the Recognizer is: {:.1f}%".format(accuracy*100))


Accuracy of the Recognizer is: 68.2%


**Saving the predictions in a .csv file**

In [ ]:
import pandas as pd
y_pred1 = pd.DataFrame(y_pred , columns=['Predictions'])
y_pred1['Name of Files'] = test_filename
print(y_pred1)
y_pred1.to_csv('FinalPredictions.csv')

    Predictions             Name of Files
0         angry  03-01-03-01-01-01-01.wav
1         happy  03-01-07-01-02-01-22.wav
2          calm  03-01-02-01-02-02-22.wav
3         angry  03-01-05-01-02-02-19.wav
4          calm  03-01-07-01-02-01-05.wav
..          ...                       ...
187        calm  03-01-02-02-02-02-13.wav
188       angry  03-01-05-01-01-01-16.wav
189       angry  03-01-05-01-01-02-13.wav
190       happy  03-01-03-02-01-02-20.wav
191     disgust  03-01-03-01-01-02-07.wav

[192 rows x 2 columns]


In [ ]:
y_pred1[:10]

Predictions             Name of Files
0       angry  03-01-03-01-01-01-01.wav
1       happy  03-01-07-01-02-01-22.wav
2        calm  03-01-02-01-02-02-22.wav
3       angry  03-01-05-01-02-02-19.wav
4        calm  03-01-07-01-02-01-05.wav
5       angry  03-01-05-01-02-02-22.wav
6       happy  03-01-03-01-02-01-14.wav
7     disgust  03-01-07-02-02-02-06.wav
8       angry  03-01-03-02-01-01-11.wav
9     disgust  03-01-07-01-02-01-21.wav

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1_score(y_test, y_pred,average=None)

array([0.78899083, 0.73529412, 0.33333333, 0.70886076])

In [ ]:
df=pd.DataFrame({'Actual': y_test, 'Predicted':y_pred})
df.head(20)

Actual Predicted
0     happy     angry
1   disgust     happy
2      calm      calm
3     angry     angry
4   disgust      calm
5     angry     angry
6     happy     happy
7   disgust   disgust
8     happy     angry
9   disgust   disgust
10  disgust     angry
11    happy     happy
12  disgust      calm
13    angry   disgust
14     calm     happy
15  disgust     angry
16    happy     angry
17    angry     angry
18    angry     angry
19  disgust      calm

In [ ]:
import pickle
# Writing different model files to file
with open( 'modelForPrediction1.sav', 'wb') as f:
    pickle.dump(model,f)

**Test the model with any other data**

In [ ]:
filename = 'modelForPrediction1.sav'
loaded_model = pickle.load(open(filename, 'rb')) # loading the model file from the storage

feature=extract_feature("/content/drive/MyDrive/archive/03-01-02-01-01-01-10.wav", mfcc=True, chroma=True, mel=True)

feature=feature.reshape(1,-1)

prediction=loaded_model.predict(feature)
prediction

array(['happy'], dtype='<U7')

In [ ]:
feature

array([[-5.63782654e+02,  7.93052902e+01, -8.40268326e+00,
         1.44333916e+01,  3.50221705e+00,  7.56285143e+00,
        -1.66794987e+01,  2.37434530e+00, -1.39347830e+01,
        -1.11347628e+01, -5.29616022e+00, -6.10221910e+00,
         3.72483683e+00, -2.75351465e-01, -8.79493332e+00,
         2.19395590e+00,  6.49870276e-01, -7.04361022e-01,
        -1.45435357e+00, -3.60424161e-01, -8.76247287e-01,
        -3.39200711e+00, -1.57573390e+00, -4.70921516e+00,
        -6.90089846e+00, -1.67140424e+00, -3.52383542e+00,
        -2.10166883e+00, -2.79078507e+00, -5.39135039e-01,
        -4.93157089e-01, -2.76499414e+00, -1.10146737e+00,
         2.85862041e+00,  2.15003037e+00,  2.78084731e+00,
         5.33906269e+00,  4.35868311e+00,  2.98552799e+00,
         4.62815428e+00,  5.60562730e-01,  5.33737123e-01,
         5.95753789e-01,  5.95510423e-01,  6.14042521e-01,
         6.47315025e-01,  6.77270591e-01,  6.81112826e-01,
         6.72933936e-01,  6.91844821e-01,  6.67901695e-0

In [ ]:
filename = 'modelForPrediction1.sav'
loaded_model = pickle.load(open(filename, 'rb')) # loading the model file from the storage

feature=extract_feature("/content/drive/MyDrive/archive/03-01-01-01-01-01-01.wav", mfcc=True, chroma=True, mel=True)

feature=feature.reshape(1,-1)

prediction=loaded_model.predict(feature)
prediction

array(['calm'], dtype='<U7')

In [ ]:
feature

array([[-7.26217224e+02,  6.85414200e+01,  3.29339767e+00,
         1.22053003e+01,  5.51027775e+00,  1.36674099e+01,
        -2.98382854e+00,  3.09802914e+00, -3.31081343e+00,
        -1.56438446e+00, -7.86165237e+00, -2.12428164e+00,
         2.84920406e+00, -2.66780639e+00,  9.59020197e-01,
         1.62816656e+00, -2.73668885e+00,  2.54240990e-01,
         2.67537737e+00, -1.76116550e+00, -1.88647425e+00,
        -9.75619972e-01, -3.79437268e-01,  4.00272876e-01,
        -3.04404378e+00, -2.90125823e+00, -1.09248057e-01,
        -8.63565266e-01, -3.33326936e+00, -1.97846520e+00,
         4.57081467e-01, -1.39910948e+00, -2.92685509e+00,
         1.39567470e-02, -4.90733683e-01, -5.70905447e-01,
         4.03992198e-02, -1.20721745e+00, -1.59498155e+00,
        -1.43648744e+00,  7.62991130e-01,  7.86087215e-01,
         7.68469393e-01,  7.68762171e-01,  7.73639500e-01,
         7.66558707e-01,  7.70558536e-01,  7.64969945e-01,
         7.80013800e-01,  7.60865748e-01,  7.59408653e-0